# this file is used to run Elastiflix in production mode using environment variables.
services:
  elastiflix:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ES_API=${ES_BACKEND}/api
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "17700:17700"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - ES_HOST=${ELASTIFLIX_ES_HOST}
      - ES_API_KEY=${ELASTIFLIX_ECH_API_KEY}
      - ES_INDEX=${ELASTIFLIX_ES_INDEX}
    volumes:
      - ./backend/src:/app/src