services:
  elastiflix:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SEARCH_ES=https://elastiflix-dev-9-0.es.us-central1.gcp.cloud.es.io
      - REACT_APP_SEARCH_API_KEY=${ELASTIFLIX-ECH-API-KEY}
      - REACT_APP_SEARCH_INDEX=elastiflix-movies
    volumes:
      - ./src:/app/src
