services:
  elastiflix:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ES_API=http://localhost:17700/api
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "17700:17700"
    environment:
      - LOCAL=true
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - ES_HOST=https://es_host_here.es.us-east-1.aws.elastic.cloud:443
      - ES_API_KEY=api_key_here
      - ES_INDEX=elastiflix-movies
    volumes:
      - ./backend/src:/app/src