services:
  elastiflix:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SEARCH_ES=${ES_PROXY}
      - REACT_APP_SEARCH_INDEX=elastiflix-movies
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    depends_on:
      - proxy

  proxy:
    build: ./nginx-proxy
    ports:
      - "17700:17700"
    environment:
      - ES_URL=https://elastiflix-dev-9-0.es.us-central1.gcp.cloud.es.io
      - ES_API_KEY=${ELASTIFLIX_ECH_API_KEY}
    restart: unless-stopped
