services:
  elastiflix:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SEARCH_ES=https://elastiflix-dev-9-0.es.us-central1.gcp.cloud.es.io
      - REACT_APP_SEARCH_API_KEY=T1pyZkRwUUJnSXFHY1NzQS1WOHY6a0J0TXZ6YjVUQmF3eFdUZjZjQ2tBUQ==
      - REACT_APP_SEARCH_INDEX=elastiflix-movies
    restart: unless-stopped
    volumes:
      - ./src:/app/src
